export const theme = {
  colors: {
    primary: "#2563EB",
    primaryDark: "#1D4ED8",
    primarySoft: "#EFF6FF",
    black: "#0A0A0A",
    white: "#FFFFFF",
    blue: "#2563EB",
    blueSoft: "#EFF6FF",
    yellow: "#FACC15",
    yellowSoft: "#FEF9C3",
    success: "#16A34A",
    warning: "#F59E0B",
    danger: "#DC2626",
    base: "#FFFFFF",
    background: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceMuted: "#F5F5F5",
    text: "#0A0A0A",
    textSecondary: "#525252",
    textTertiary: "#8A8A8A",
    border: "#E5E5E5",
    divider: "#EEEEEE",
  },
  base: {
    background: "#FFFFFF",
    appBackground: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceMuted: "#F5F5F5",
  },
  neutral: {
    textPrimary: "#0A0A0A",
    textSecondary: "#525252",
    textTertiary: "#8A8A8A",
    border: "#E5E5E5",
    divider: "#EEEEEE",
  },
  accents: {
    action: "#2563EB",
    actionSoft: "#EFF6FF",
    achievement: "#FACC15",
    achievementSoft: "#FEF9C3",
    success: "#16A34A",
    warning: "#F59E0B",
    danger: "#DC2626",
  },
  typography: {
    ui: '"Plus Jakarta Sans", Inter, system-ui, sans-serif',
    heading: '"Plus Jakarta Sans", Manrope, Inter, system-ui, sans-serif',
    pageTitle: "22px",
    sectionTitle: "17px",
    cardTitle: "16px",
    body: "14px",
    meta: "12px",
    metric: "30px",
  },
  fontWeights: {
    body: 450,
    metadata: 500,
    label: 600,
    title: 700,
    metric: 750,
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    "2xl": "32px",
  },
  layout: {
    sectionGap: "18px",
    rowHeight: "64px",
    rowPaddingY: "12px",
    rowPaddingX: "0px",
    listDivider: "#EEEEEE",
    gridGap: "12px",
  },
  radius: {
    card: "16px",
    small: "12px",
    button: "999px",
    input: "12px",
    nav: "24px",
    avatar: "999px",
  },
  shadows: {
    card: "0 8px 24px rgba(10, 10, 10, 0.04)",
    floating: "0 12px 32px rgba(10, 10, 10, 0.10)",
    button: "0 6px 16px rgba(10, 10, 10, 0.12)",
  },
  iconSizes: {
    xs: 16,
    sm: 18,
    md: 20,
    lg: 24,
    xl: 28,
  },
  iconStroke: {
    regular: 1.8,
    strong: 2.0,
  },
  header: {
    height: 58,
    paddingX: 20,
    background: "#FFFFFF",
    border: "#E5E5E5",
    titleSize: 21,
    titleWeight: 700,
  },
  navigation: {
    active: "#2563EB",
    inactive: "#8A8A8A",
    labelSize: 10,
    labelWeight: 600,
  },
};

export const C = theme.colors;
